=== talentappstore/tas-tenant-apis/docs/schemas/applicationView.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "definitions": {
    "internalFlag": {
      "type": "boolean",
      "description": "whether this candidate is an internal"
    },
    "candidate": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer"
        },
        "vcard": {
          "$ref": "jcard.json"
        },
        "internalFlag": {
          "$ref": "#/definitions/internalFlag"
        },
        "resumeMeta": {
          "$ref": "fileDownload.json"
        },
        "items": {
          "$ref": "itemsRead.json"
        }
      },
      "required": [
        "vcard",
        "resumeMeta",
        "internalFlag",
        "items"
      ]
    },
    "application": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer"
        },
        "items": {
          "$ref": "itemsRead.json"
        }
      },
      "required": [
        "items"
      ]
    },
    "remuneration": {
      "type": "object",
      "description": "See HR/XML OnBoardingDeploymentType",
      "properties": {
        "amount": {
          "type": "number",
          "description": "The monetary value of the object in which the amount is associated"
        },
        "rateIntervalCode": {
          "type": "string",
          "description": "See HR/XML PayRateIntervalCodeType"
        },
        "typeCode": {
          "type": "string",
          "description": "A code classifying the type of remuneration (HR/XML)"
        }
      },
      "additionalProperties": false
    },
    "dutyEntryDate": {
      "type": "string",
      "format": "date-time",
      "description": "Per- HR-XML, the date the employee or human resource actually begins work or enters on duty"
    },
    "hireDate": {
      "type": "string",
      "format": "date-time",
      "description": "Per- HR-XML, The date on which the associated person was hired."
    },
    "onBoardedDate": {
      "type": "string",
      "format": "date-time",
      "description": "The date on which the associated person completed onboarding."
    },
    "hireDetails": {
      "type": "object",
      "properties": {
        "remuneration": {
          "$ref": "#/definitions/remuneration"
        },
        "dutyEntryDate": {
          "$ref": "#/definitions/dutyEntryDate"
        },
        "hireDate": {
          "$ref": "#/definitions/hireDate"
        },
        "onBoardedDate": {
          "$ref": "#/definitions/onBoardedDate"
        }
      },
      "additionalProperties": false
    }
  },
  "type": "object",
  "properties": {
    "application": {
      "$ref": "#/definitions/application"
    },
    "job": {
      "$ref": "jobRead.json"
    },
    "candidate": {
      "$ref": "#/definitions/candidate"
    },
    "job.manager": {
      "$ref": "user.json"
    },
    "hireDetails": {
      "$ref": "#/definitions/hireDetails"
    }
  },
  "additionalProperties": false
}

=== talentappstore/tas-tenant-apis/docs/examples/applicationView-simple.json
{
  "application": {
    "items": [
      {
        "name": "birthdate",
        "type": "date",
        "value": "2015-11-05T13:15:30Z"
      },
      {
        "name": "keenworkerflag",
        "type": "boolean",
        "value": true
      },
      {
        "name": "minsalary",
        "type": "number",
        "value": 120000.50
      },
      {
        "name": "coverletter",
        "type": "file",
        "value": {
          "fileName": "fredcv.docx",
          "size": 3023443,
          "mediaType": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
          "dateUploaded": "2015-11-05T13:15:30Z",
          "preSignedUri": "https://frodo.com/docs/198714509"
        }
      },
      {
        "name": "mypicks",
        "type": "picklist",
        "value": [
          {
            "choice": "choice1"
          },
          {
            "choice": "choice2",
            "subItems": [
              {
                "name": "myreason",
                "type": "string",
                "value": "just because"
              }
            ]
          }
        ]
      }
    ]
  },
  "hireDetails": {
    "hireDate": "2015-11-05T13:15:30Z"
  },
  "job": {
    "code": "TTfg321",
    "title": "Creative Director",
    "items": []
  },
  "candidate": {
    "vcard": {},
    "internalFlag": false,
    "resumeMeta": {
      "fileName": "fredcv.docx",
      "size": 3023443,
      "mediaType": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      "dateUploaded": "2015-11-05T13:15:30Z",
      "preSignedUri": "https://frodo.com/docs/198714509"
    },
    "items": []
  },
  "job.manager": {}
}
