=== talentappstore/tas-tenant-apis/docs/schemas/applicationShell.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "definitions": {
    "source": {
      "type": "string"
    },
    "tracker": {
      "type": "integer"
    },
    "formFactor": {
      "enum": [
        "mobile",
        "desktop",
        "tablet",
        "other"
      ]
    },
    "bucketMovement": {
      "type": "object",
      "properties": {
        "key": {
          "type": "string"
        },
        "landed": {
          "type": "string",
          "format": "date-time"
        }
      },
      "additionalProperties": false,
      "required": [
        "key",
        "landed"
      ]
    },
    "bucketMovements": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/bucketMovement"
      }
    },
    "job": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer"
        }
      },
      "additionalProperties": false,
      "required": [
        "id"
      ]
    },
    "candidate": {
      "$ref": "person.json"
    }
  },
  "type": "object",
  "properties": {
    "id": {
      "type": "integer"
    },
    "source": {
      "$ref": "#/definitions/source"
    },
    "tracker": {
      "$ref": "#/definitions/tracker"
    },
    "formFactor": {
      "$ref": "#/definitions/formFactor"
    },
    "job": {
      "$ref": "#/definitions/job"
    },
    "candidate": {
      "$ref": "#/definitions/candidate"
    },
    "dateLastUpdated": {
      "$ref": "applicationRead.json#/definitions/dateLastUpdated"
    },
    "bucketMovements": {
      "$ref": "#/definitions/bucketMovements"
    }
  },
  "additionalProperties": false,
  "required": [
    "id",
    "source",
    "formFactor",
    "job",
    "candidate",
    "dateLastUpdated"
  ]
}

=== talentappstore/tas-tenant-apis/docs/examples/applicationShells-simple.json
[
  {
    "id": 10045434,
    "source": "seek-camp0",
    "formFactor": "mobile",
    "job": {
      "id": 3443
    },
    "candidate": {
      "id": 4988,
      "givenName": "Fred",
      "familyName": "Flintstone"
    },
    "bucketMovements": [
      {
        "key": "incoming",
        "landed": "2017-05-29T01:34:30+00:00"
      },
      {
        "key": "prescreen",
        "landed": "2017-05-29T01:34:30+00:00"
      },
      {
        "key": "interview",
        "landed": "2017-05-29T01:34:30+00:00"
      }
    ],
    "dateLastUpdated": "2017-05-29T01:34:30+00:00"
  },
  {
    "id": 10045437,
    "source": "trademe",
    "formFactor": "desktop",
    "job": {
      "id": 3443
    },
    "candidate": {
      "id": 4988,
      "givenName": "Sheila",
      "familyName": "Jones"
    },
    "bucketMovements": [
      {
        "key": "incoming",
        "landed": "2017-05-29T01:34:30+00:00"
      },
      {
        "key": "prescreen",
        "landed": "2017-05-29T01:34:30+00:00"
      },
      {
        "key": "interview",
        "landed": "2017-05-29T01:34:30+00:00"
      }
    ],
    "dateLastUpdated": "2017-05-29T01:34:30+00:00"
  },
  {
    "id": 10045444,
    "source": "trademe",
    "formFactor": "tablet",
    "job": {
      "id": 3443
    },
    "candidate": {
      "id": 4993,
      "givenName": "Fred",
      "familyName": "Bloggs"
    },
    "bucketMovements": [
      {
        "key": "incoming",
        "landed": "2017-05-29T01:34:30+00:00"
      },
      {
        "key": "prescreen",
        "landed": "2017-05-29T01:34:30+00:00"
      },
      {
        "key": "interview",
        "landed": "2017-05-29T01:34:30+00:00"
      }
    ],
    "dateLastUpdated": "2017-05-29T01:34:30+00:00"
  }
]
