=== talentappstore/tas-tenant-apis/docs/schemas/jobWrite.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "type": "object",
  "properties": {
    "status": {
      "$ref": "jobRead.json#/definitions/status"
    },
    "availability": {
      "$ref": "jobRead.json#/definitions/availability"
    },
    "code": {
      "$ref": "jobRead.json#/definitions/code"
    },
    "title": {
      "$ref": "jobRead.json#/definitions/title"
    },
    "shortSummary": {
      "$ref": "jobRead.json#/definitions/shortSummary"
    },
    "company": {
      "$ref": "jobRead.json#/definitions/company"
    },
    "country": {
      "$ref": "jobRead.json#/definitions/country"
    },
    "manager": {
      "$ref": "userRead.json"
    },
    "categories": {
      "$ref": "categoriesActual.json"
    },
    "items": {
       "$ref": "itemsWrite.json"
    }
  },
  "additionalProperties": false
}

=== talentappstore/tas-tenant-apis/docs/examples/jobWrite-create.json
{
  "status": "active",
  "availability": {
    "availableInternally": true,
    "availableExternally": true,
    "applicationCloseDates": {
      "closeDate": "2015-11-05T13:15:30Z"
    }
  },
  "code": "1022NH",
  "title": "Creative Director",
  "shortSummary": "One in a life time opportunity to work with a bunch of great people that do their job with a passion!",
  "country": "US",
  "categories": [
    {
      "category": 100001999,
      "values": [
        100115552,
        100115513
      ]
    },
    {
      "category": 100037613,
      "values": [
        100114669,
        100114660,
        100114642,
        100114666
      ]
    },
    {
      "category": 100015632,
      "values": [
        100015637
      ]
    },
    {
      "category": 100039352,
      "values": [
        100039361
      ]
    }
  ]
}
