=== talentappstore/tas-tenant-apis/docs/schemas/postingRead.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "definitions": {
    "id": {
      "type": "integer"
    },
    "status": {
      "enum": [
        "draft",
        "open",
        "closed"
      ]
    },
    "statusMessage": {
      "type": "string",
      "description": "e.g. listing expired, job closed, error - missing blah,  etc."
    },
    "scheduledCloseDate": {
      "type": "string",
      "format": "date-time",
      "description": "when the posting should be closed by the hub."
    },
    "actualCloseDate": {
      "type": "string",
      "format": "date-time",
      "description": "when the posting in the hub actually was closed"
    },
    "linkout": {
      "type": "string",
      "format": "uri",
      "description": "link to the job on the career site with source tracking attached"
    },
    "recruiterName": {
      "type": "string"
    },
    "recruiterEmail": {
      "type": "string"
    },
    "recruiterTeam": {
      "type": "string"
    },
    "contactPersonName": {
      "type": "string"
    },
    "contactPersonEmail": {
      "type": "string"
    },
    "applicationEmail": {
      "type": "string"
    },
    "customFieldsJson": {
      "type": "string",
      "description": "e.g. advertiser profile, template, premium features, video"
    },
    "previewLink": {
      "type": "string",
      "format": "uri",
      "description": "link to the posting on the job board"
    }
  },
  "type": "object",
  "properties": {
    "id": {
      "$ref": "#/definitions/id"
    },
    "status": {
      "$ref": "#/definitions/status"
    },
    "statusMessage": {
      "$ref": "#/definitions/statusMessage"
    },
    "scheduledCloseDate": {
      "$ref": "#/definitions/scheduledCloseDate"
    },
    "actualCloseDate": {
      "$ref": "#/definitions/actualCloseDate"
    },
    "linkout": {
      "$ref": "#/definitions/linkout"
    },
    "recruiterName": {
      "$ref": "#/definitions/recruiterName"
    },
    "recruiterEmail": {
      "$ref": "#/definitions/recruiterEmail"
    },
    "recruiterTeam": {
      "$ref": "#/definitions/recruiterTeam"
    },
    "contactPersonName": {
      "$ref": "#/definitions/contactPersonName"
    },
    "contactPersonEmail": {
      "$ref": "#/definitions/contactPersonEmail"
    },
    "applicationEmail": {
      "$ref": "#/definitions/applicationEmail"
    },
    "customFieldsJson": {
      "$ref": "#/definitions/customFieldsJson"
    },
    "title": {
      "$ref": "jobRead.json#/definitions/title"
    },
    "code": {
      "$ref": "jobRead.json#/definitions/code"
    },
    "description": {
      "$ref": "jobRead.json#/definitions/description"
    },
    "categories": {
      "$ref": "categoriesActual.json"
    },
    "previewLink": {
      "$ref": "postingRead.json#/definitions/previewLink"
    }
  }
}

=== talentappstore/tas-tenant-apis/docs/examples/postingRead-simple.json
{
    "id": 100,
    "status": "open",
    "linkout": "https://blah.com/job/10033",
    "title": "CEO",
    "code": "GR5022",
    "description": "This is an exciting position.",
    "categories": [
        {
            "category": 1022,
            "values": [
                10024
            ]
        },
        {
            "category": 1026,
            "values": [
                10044,
                10025,
                10029
            ]
        }
    ],
    "customFieldsJson": "json goes here"
}
