=== talentappstore/tas-tenant-apis/schemas/buttonDetail.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"type": "object",
	"description": "the logical information needed to populate a button, excluding style information (which is down to the app rendering the button)",
	"properties": {
		"icon": {
			"type": "string",
			"format": "uri",
			"description": "the url of an image that will be rendered within the button - should be 64 x 64 pixels in size"
		},
		"label": {
			"type": "string",
			"description": "the text of the button"
		},
		"behavior": {
			"description": "when the button is clicked and a uri is present: either the user is redirected, or a popup renders the uri inside a modal (inside an iframe)",
			"enum": ["redirect", "modal"]
		},
		"uri": {
			"type": "string",
			"format": "uri",
			"description": "the url that the button will redirect the user to when the button is pressed, or use to populate an iframe inside a modal"
		},
		"backgroundColor": {
			"type": "string",
			"description": "the background color of the button, in hex format, without leading #, upper case letters (e.g. '22DD33')"
		},
		"textColor": {
			"type": "string",
			"description": "the color of the button's text, in hex format, without leading #, upper case letters (e.g. '22DD33')"
		},
		"disabled": {
			"type": "boolean",
			"description": "true if the button should appear disabled"
		}
	}
}

=== talentappstore/tas-tenant-apis/examples/buttonDetails-simple.json
[
{
	"icon": "http://examples.com/images/cat.png",
	"label": "Refer a friend",
	"behavior": "redirect",
	"uri": "https://referrals.com/jobs/1022?tracker=106645",
	"backgroundColor": "00DDEE",
	"textColor": "FF5522",
	"disabled": false
},
{
	"icon": "http://examples.com/images/dog.png",
	"label": "Share this job",
	"behavior": "modal",
	"uri": "https://sharing.com/jobs/1022?tracker=106645",
	"backgroundColor": "1133FF",
	"textColor": "FF3311",
	"disabled": false
}
]
